"""add unique constraints

Revision ID: 08224c82d4dc
Revises: 7d373d36e792
Create Date: 2026-02-15 16:47:51.466288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08224c82d4dc'
down_revision: Union[str, Sequence[str], None] = '7d373d36e792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'buildings', ['address'])
    op.create_unique_constraint(None, 'companies', ['name'])
    op.create_unique_constraint(None, 'industries', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'industries', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint(None, 'buildings', type_='unique')
    # ### end Alembic commands ###
